version: "3.1"

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: adonis
      POSTGRES_USER: gmoreiratdj
      POSTGRES_PASSWORD: Web!783195
    ports:
      - 15432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8088:8080
